django/app/urls.py
"""URL patterns for main app"""

#Import Libraries/Modules
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'app'

urlpatterns = [
	#Home Page
	path('', views.index, name='index'),
	#Movies Page
	path('movies', views.movies,  name='movies'),
	#Recommend Movies Page
	path('camera_page', views.camera_page,  name='camera_page'),
	#Open Camera Function
    path('display_camera_frame/', views.display_camera_frame, name='display_camera_frame'),
    #Run Main Website Function and return results in emotion_and_movies.html page
	path('get_emotion_and_images/', views.get_emotion_and_images, name='get_emotion_and_images')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #Include url to static folder where all  additional files are stored

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #Url to Media folder (future addition)

django/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
	path('', include('django.contrib.auth.urls')),
	path('register/', views.register, name='register'),
]

django/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('app.urls')),
]

django/app/models.py
from django.db import models

# Create your models here.

django/users/models.py
from django.db import models

# Create your models here.

django/app/views.py
#Import Libraries 
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http.response import StreamingHttpResponse
from django.conf import settings
import tensorflow as tf
from tensorflow.keras.models import load_model
global graph, model
import pandas as pd
import numpy as np
from .camera import VideoCamera
import cv2
import base64



###TENSORFLOW GPU OPERATIONS###
#Fraction of the available GPU memory to allocate for each process.
config = tf.compat.v1.ConfigProto(gpu_options =
                         tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.8))
config.gpu_options.allow_growth = True
#Environment to set and run TensorFlow operations
session = tf.compat.v1.Session(config=config)
tf.compat.v1.keras.backend.set_session(session)



###LOAD DEEP LEARNING MODELS###
#Face Detection Model
face_cascade = cv2.CascadeClassifier(f"{settings.STATICFILES_DIRS[0]}/models/haarcascade_frontalface_default.xml")
#Emotion Classification Model
model = load_model(settings.STATICFILES_DIRS[0] + "/models/FERmodel.h5")

###LOAD DATASETS###
#Load MovieLens Dataset (includes movie title-genre-rating correlation)
df = pd.read_csv(f"{settings.STATICFILES_DIRS[0]}/movies_metadata.csv")
df['genres'] = df['genres'].apply(lambda x: [i['name'] for i in eval(x)])


#Initialize Labels/Classes for emotion classifier
classes = {
	"0": "Angry",
	"1": "Happy",
	"2": "Sad",
	"3": "Neutral"
}

#Initialize emotion-movie genre mappings
emotion_genre_map = {
	"Angry": ["Action", "Adventure", "Crime", "Thriller"],
	"Happy": ["Comedy", "Family", "Mystery"],
	"Sad": ["Romance", "Music", "Science Fiction"],
	"Neutral": ["Documentary", "History", "Animation"]
}






#-----###MAIN FUNCTIONS###-----#



#Django-Python manipulation, to open page upon url call.#

def index(request):
	"""Opens Home Page when url is requested."""
	context={'a':1}
	return render(request,'app/index.html',context)


def movies(request):
	"""Opens Browse Movies Page when url is requested."""
	return render(request, 'app/movies.html')


def camera_page(request):
	"""Opens Recommend Movies Page when url is requested."""
	context={'a':1}
	return render(request, 'app/camera_page.html',context)




#CAMERA MANIPULATION#

def display_camera_frame(request):
	"""Opens and Displays Camera after request from camera_page.html page"""
	camera = VideoCamera()
	response = StreamingHttpResponse(start_camera(camera), content_type='multipart/x-mixed-replace; boundary=frame')
	return response


def start_camera(camera):
	"""Captures frame/image from Camera."""
	frame_index = 0
	while True:
		frame = camera.get_frame()
		if frame_index%10 == 0:
			with open(f"{settings.STATICFILES_DIRS[0]}/images/face", "wb+") as f:
				f.write(frame)
			f.close()
		frame_index+=1
		yield (b'--frame\r\n'
			   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


def ndarray_to_b64(ndarray):
    """Converts an np ndarray to a binary string readable by html-img tags."""
    img = cv2.cvtColor(ndarray, cv2.COLOR_RGB2BGR)
    _, buffer = cv2.imencode(".png", img)
    return base64.b64encode(buffer).decode("utf-8")




#Emotion Classification/Movie recommendation Functions


def get_emotion_and_images(request):
	"""Returns Image with detected face and movie recommendation results.""" 
	print(f"{settings.STATICFILES_DIRS[0]}/models/haarcascade_frontalface_default.xml")
	fd = open(f'{settings.STATICFILES_DIRS[0]}/images/face', "rb")
	img_str = fd.read()
	fd.close()

	nparr = np.frombuffer(img_str, np.uint8)
	image = cv2.imdecode(nparr, cv2.IMREAD_COLOR) 
	image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

	image, emotion = get_image_frame_and_emotion(image)

	recommended_movies = get_recommended_movies(emotion)

	context={"image_src":f"data:image/png;base64,{ndarray_to_b64(image)}",
			 "recommended_movies": recommended_movies}

	return render(request, 'app/emotion_and_movies.html', context)



def get_image_frame_and_emotion(image):
	"""Detects user's face in captured image and predicts the emotion. Then draws both in the image.""" 
	width = image.shape[0]
	height = image.shape[1]

	#gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
	detect_face = face_cascade.detectMultiScale(image, scaleFactor=1.1, minNeighbors=6, minSize=(197, 197),
												flags=cv2.CASCADE_SCALE_IMAGE)
	for (x, y, w, h) in detect_face:
		input_img = np.expand_dims(cv2.resize(image[x:x+w, y:y+h], (197,197)), 0)
		input_img = input_img/255
		predictions = model.predict(input_img)
		emotion = classes[str(np.where(predictions == np.max(predictions))[1][0])]

		cv2.rectangle(image, (x, y), (x + w, y + h), (255, 0, 0), 2)
		cv2.putText(image, emotion, (x, y+h + 30), cv2.FONT_HERSHEY_PLAIN, 2, (255, 0, 0), 2)
		break

	return image, emotion



def get_recommended_movies(emotion):
	"""Chooses the 20 top rated movies in the specific genre according to emotion-genre mapping. 
	It randomly suggests 5 out of 20 each time.""" 
	movies = list(df[df["genres"].apply(lambda x: movie_recommended(x, emotion))].sort_values("vote_average",
																							  ascending=False).iloc[
				  :20].sample(5)["original_title"])
	return movies



def movie_recommended(movie_genres, emotion):
	"""Confirm Genres according to emotion-genre mapping.""" 
	for genre in emotion_genre_map[emotion]:
		if genre in movie_genres:
			return True
	return False

django/users/views.py
#Import Libraries
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required


#---###MAIN FUNCTIONS###---#


def register(request):
	"""Register new user form."""
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			login(request, new_user)
			return redirect('app:index')
	context = {'form': form}
	return render(request, 'registration/register.html', context)

django/app/templates/app/base.html
<!-- A Parent Template for all HTML pages, they inherit the basic structure from -->
{% load bootstrap4 %}


<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=yes">
	<title>Feelings - Beta</title>

	<!--STYLING/JAVASCRIPT SHEETS-->
		<!--Bootstrap's CSS Template-->
		{% bootstrap_css %}
		<!--Bootstrap's JavaScript and jQuery Templates, allows use of ready-made functional components-->
		{% bootstrap_javascript jquery='full' %}
		<!--Custom JavaScript Sheet-->
		<script src="static/script.js"></script>
		<!--Custom CSS Style Sheet, includes Styling for all pages within the website-->
		<link rel="stylesheet" href="static/style.css">

	<!-- GOOGLE FONTS -->
		<!--Main Logo Font Style-->
		<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
		<!--Page Headers Font Style-->
		<link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
		<!--Movies Page - Genre Titles Font Style-->
		<link href="https://fonts.googleapis.com/css2?family=Poppins:ital@1&display=swap" rel="stylesheet">
</head>

<!--MAIN BODY-->
<body>
	<div class="hero">
		<!--Create the navigation bar and set a light colour background, make the page logo a link to home page-->
		<nav id="navbar" class="navbar sticky-top navbar-expand-md navbar-light bg-warning mb-4 border">
			<a id="logo" class="navbar-brand" href="{% url 'app:index'%}">
				Feelings//</a>

			<!--Create drop down navigation list when screen size reduces-->		
			<button class="navbar-toggler" type="button" data-toggle="collapse"
				data-target="#navbarCollapse" aria-controls="navbarCollapse"
				aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-tpggler-icon"></span></button>

			<!--Create a holding place in the nav bar for future pages within website-->
			<div style="font-weight: bold;" class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav mr-auto">
					<li class="btn btn-light bg-warning" style="font-weight: bold;"><a class="nav-link" href="{% url 'app:camera_page' %}">Recommend Movies</a></li>
					<li class="btn btn-light bg-warning" style="font-weight: bold;"><a class="nav-link" href="{% url 'app:movies' %}">Browse Movies</a></li>
				</ul>

				<!--Add Register and Login links in nav bar and their actions-->
				<ul class="navbar-nav ml-auto">
					
					{% if user.is_authenticated %}
						<li class="nav-item" style="font-weight: bold; margin: 10px;">
						 	<span class="navbar-text">Hello, {{user.username}}.</span>
						</li>
						<li class="nav-item btn btn-light bg-warning" style="font-weight: bold;">
							<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
						</li>
					{% else %}
						<li class="nav-item btn btn-light bg-warning" style="font-weight: bold;">
							<a class="nav-link" href="{% url 'users:register' %}">Register</a>
						</li>
						<li class="nav-item btn btn-light bg-warning" style="font-weight: bold;">
							<a class="nav-link" href="{% url 'users:login' %}">Login</a>
						</li>
					{% endif %}
				</ul>

				<!-- Search Bar-->
				<!--
				<form class="form-inline">
	    		<input class="form-control form-control-sm mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	    		<button class="btn btn-sm btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	  			</form>
	  			-->
			
			</div>
		</nav>


		<!--Style/Provide a background structure for main body of webpages-->
		<!--Insert Header for each Page-->
		<div class="pb-2 mb-2" id="header">
			<div id="page-title">
				{% block page_header %}{% endblock page_header%}
			</div>
		</div>
		<br>
		<!--Main body, add page specific structure/elements within the block content-->
		<main role="main" class="container-fluid">
			{% block content %}{% endblock content%}
		</main>
	</div>
</body>
</html>

django/app/templates/app/camera_page.html
<!-- Recommend Movies Page (Inherits from base.html)-->
{% extends "app/base.html" %}
{% load bootstrap4 %}


<!--Page Title-->
{% block page_header %}
	<!--<p id="cam_page_title" style="background-color: white;">Get Movie Recommendations depending on your mood!!</p>-->
{% endblock page_header %}



<!--Main Body, Page Specific Content-->
{% block content %}

<!--MODAL-->
<!--add function-->
<script>
	$(document).ready(function(){
		$("#myModal").modal('show');
	});
	$("#myModal .close").click()
</script>

<!--Modal, pop up 'Instructions' Window-->
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: rgba(211,211,211,1);height: 550px;">
            <div class="modal-header">
            	<!--Title-->
                <h5 class="modal-title">Instructions</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!--Main Body-->
            <div class="modal-body container">
            	<div id="text" class="row">
            		<div class="col">
            			<p>Place your face to a close distance against your camera, as shown to the image below. Then, try to imitate one of the four emotions shown here and press the <b>Capture</b>* button!!
            			<br><br>
            			<b style="text-decoration: underline;">Disclaimer</b>
            			<br>
            			As this is a beta version, please be aware that the algorithm for recognizing emotions, it will not be accurate at all times. It has an accuracy of 73-76%.
            			<br><br>
            			<i style="font-size: 13;">Please allow few seconds for your webcam to open.</p>
            		</div>
            	</div>

            	<!--Images Container/Row-->
                <div class="form-group row">
	                <div class="col" id="col1"><img id="img" src="static/images/camera_page/angry.jfif"><figcaption>Angry</figcaption></div>
	                <div class="col" id="col2"><img id="img" src="static/images/camera_page/happy.jfif"><figcaption>Happy</figcaption></div>
	                <div class="col" id="col3"><img id="img" src="static/images/camera_page/sad.jfif"><figcaption>Sad</figcaption></div>
	                <div class="col" id="col4"><img id="img" src="static/images/camera_page/neutral.jfif"><figcaption>Neutral</figcaption></div>
                </div>

                <!--Footer Row-->
               	<div class="row">
               		<div class="col">
              			<p style="font-size: 11px;"><i>*Images are not being saved in memory. After leaving or refreshing the page, they disappear.</i></p>
              		</div>
              	</div>
            </div>
        </div>
    </div>
</div>
<!--END MODAL-->


<!--CAMERA STRUCTURE & FUNCTION-->
<div class="container-fluid" id="cam_page">
	<div class="row">
		<div class="col" id="column1">
			<div id="open_cam"><img id="face_image" width="510" height="360" src="{% url 'app:display_camera_frame'%}"></div>
			<br>
			<div id="button"><button id="snap" class="btn btn-primary" onclick="get_emotion()">Capture</button></div>
		</div>
		<div class="col" id="column2">
			<div style="font-family: 'Poppins', sans-serif;" id="screenshot"></div>
		</div>
	</div>

	<!--Questionnaire URL-->
	<div class="row" id="questionnaire">
		<a style="color: white;" href="https://forms.gle/qXd2qKFi64dG8UWo9" target="_blank">Please answer the questionnaire</a>
	</div>

</div>

<!--add function-->
<script>
	function get_emotion(){
		$.ajax({
            url: "{% url 'app:get_emotion_and_images' %}",
			data: {src: document.getElementById("face_image").src},
            type: "GET",
            cache: false,
        }).then(function (response) {
		$('#screenshot').html(response)
	});
	}
</script>
<!--END CAMERA FUNCTIONS-->


{% endblock content %}

django/app/templates/app/emotion_and_movies.html
<!--Embedded Result Page, it displays recommendation results within amera_page.html-->

<!--Display screenshot taken from live feed-->
<img src="{{image_src}}" width="360" height="280" style="margin-bottom: 10px; border: 8px solid gray; border-radius: 14px;">


<!--Print Results-->
<h2 style="font-size: 18px; text-decoration: underline; font-weight: bold; padding-bottom: 5px;">We recommend these movies for you:</h2>
{% for i in recommended_movies %}
    <h4 style="font-size: 18px;">{{ forloop.counter}}) {{i}}</h4>
{% endfor %}

django/app/templates/app/index.html
<!--Home Page (Inherits from base.html)-->
{% extends "app/base.html" %}
{% load bootstrap4 %}



<!--Page Title-->
{% block page_header %}
	<p style="background-color: rgba(255,255,255, 0.7);">Welcome</p>
{% endblock page_header %}



<!--Main Body, Page Specific Content-->
{% block content%}
<!--Welcome Message Window-->
<div id="main-text">
	<!--Text-->
	<div id="main-text-borders">
		<!-- Text Message-->
		<br><h6>Hey there,
			<br><br><br>
			&nbsp;&nbsp;&nbsp;This is a beta version of my final year Computer Science &nbsp;&nbsp;&nbsp;project with title <em>"Feelings - An Emotion Based Movie &nbsp;&nbsp;&nbsp;Recommendation Web-App which uses Facial Emotion &nbsp;&nbsp;&nbsp;Classification"</em>. 
			<br><br>
			&nbsp;&nbsp;&nbsp;It is still in the development phase and I would really &nbsp;&nbsp;&nbsp;appreciate if you could spare some of your time and be part &nbsp;&nbsp;&nbsp;of the <em>User Testing</em> phase. It will approximately take 15 &nbsp;&nbsp;&nbsp;minutes to complete. You are asked to take some photos of &nbsp;&nbsp;&nbsp;yourself and answer a questionnaire (contains 11 questions), &nbsp;&nbsp;&nbsp;by following the link below the camera window.
			<br><br>
			&nbsp;&nbsp;&nbsp;At this stage, the main functions are to allow users to capture &nbsp;&nbsp;&nbsp;an image of their faces, while imitating one of 4 emotions - &nbsp;&nbsp;&nbsp;Angry, Happy, Sad and Neutral. After pressing the "Capture" &nbsp;&nbsp;&nbsp;button, it will print the image taken, including the predicted &nbsp;&nbsp;&nbsp;emotion. Finally, the system will suggest relevant movie titles &nbsp;&nbsp;&nbsp;related to the captured emotion. For example, if the &nbsp;&nbsp;&nbsp;predicted emotion has been recognised as <em>"Happy"</em>, it will &nbsp;&nbsp;&nbsp;suggest movie genres that include <em>'Comedies', 'Musicals'</em> etc.

		<br>
		<br>
		<br>
		<a style="color: black; font-weight: bold;" id="take_me_there" href="{% url 'app:camera_page'%}">Take me there!</a>
		</h6>
	</div>
</div>
<!--Welcome Message Window End-->
{% endblock content%}